import { Playfair_Display } from 'next/font/google';
import { Poppins } from 'next/font/google';
import "./globals.css";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hero from "../components/Hero";

export const playfair = Playfair_Display({
  subsets: ['latin'], // required
  weight: ['400', '700'], // optional: specify the font weights you need
  style: ['normal'], // optional
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // choose what you need
  style: ['normal'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}`}
      >
        <Header playfair={playfair} poppins={poppins}/>
        <Hero playfair={playfair} poppins={poppins}/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
